version: '2'
services:
  app:
    build: .
    environment:
      - NODE_ENV=production
  sauce:
    image: ustwo/sauce-connect
    ports:
      - 8000:8000
    command: -P 8000 -u ${SAUCE_USERNAME} -k ${SAUCE_ACCESS_KEY} --tunnel-identifier foo
  chromedriver:
    image: blueimp/chromedriver
    environment:
      - VNC_ENABLED=true
      - EXPOSE_X11=true
    ports:
      - 5900:5900
  nightwatch:
    image: blueimp/nightwatch:0.9
    depends_on:
      - chromedriver
      - app
    environment:
      - WAIT_FOR_HOSTS=app:5000 chromedriver:4444 chromedriver:6060
      - SAUCE_USERNAME=${SAUCE_USERNAME}
      - SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY}
      - LAUNCH_URL=${LAUNCH_URL}
    volumes:
      - ./nightwatch:/home/node
